name: test

on: push

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - run: composer install --no-interaction
      - run: vendor/bin/phpcs

  psalm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - run: composer install --no-interaction
      - run: vendor/bin/phpunit

  phpunit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php: [ 8.0, 7.4 ]
        laravel: [ 8.*, 7.*, 6.* ]
        os: [ ubuntu-latest ]
        include:
          - laravel: 8.*
            testbench: ^6.3
          - laravel: 7.*
            testbench: ^5.8
          - laravel: 6.*
            testbench: ^4.9
    name: phpunit (P${{ matrix.php }} - L${{ matrix.laravel }})
    env:
      DB_HOST: 127.0.0.1
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
          user: loadfile
          password: loadfile-testing
          my-cnf: local_infile=1
      - run: mysql -uroot -h127.0.0.1 -e 'create database loadfile'
      - run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction
          composer update --no-interaction
      - run: vendor/bin/phpunit
